org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=true

minecraft_version=26.3
minecraft_version_range=[26.3]
neo_version=26.3.0.8-beta

mod_id=undecided
mod_name=undecided
mod_license=GPLv3-only
mod_version=1.0.0
mod_group_id=com.github.undecided
